## Regresion lineal simple de Python  paquete statsmodel

In [1]:
import pandas as pd
import statsmodels.formula.api as smf 
import numpy as np

In [2]:
DataFra = "/Users/luisalberto/Documents/Projects/ads/Advertising.csv"

data = pd.read_csv(DataFra)

In [3]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
lm = smf.ols(formula="Sales~TV", data = data).fit()

In [9]:
lm.params

Intercept    7.032594
TV           0.047537
dtype: float64

El modelo lineal predictivio seria Sales = 7.032594 + 0.047537 * TV

In [10]:
lm.pvalues

Intercept    1.406300e-35
TV           1.467390e-42
dtype: float64

## Regresion lineal multiple

In [15]:
lm2 = smf.ols(formula="Sales~TV+Newspaper", data = data).fit()

In [16]:
lm2.params

Intercept    5.774948
TV           0.046901
Newspaper    0.044219
dtype: float64

In [17]:
lm2.pvalues

Intercept    3.145860e-22
TV           5.507584e-44
Newspaper    2.217084e-05
dtype: float64

In [18]:
## Sales = 5.774948 + 0.046901TV + 0.044219NP

In [19]:
lm2.rsquared

0.6458354938293271

In [20]:
sales_pred = lm2.predict(data[["TV", "Newspaper"]])

In [21]:
sales_pred

0      19.626901
1       9.856348
2       9.646055
3      15.467318
4      16.837102
         ...    
195     8.176802
196    10.551220
197    14.359467
198    22.003458
199    17.045429
Length: 200, dtype: float64

In [23]:
SSD = sum((data["Sales"]-sales_pred)**2)

In [24]:
SSD

1918.561811896827

In [28]:
RSE = np.sqrt(SSD/(len(data)-2-1))

In [29]:
RSE

3.120719860252885

In [32]:
lm2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.646
Model:                            OLS   Adj. R-squared:                  0.642
Method:                 Least Squares   F-statistic:                     179.6
Date:                Sun, 31 Jul 2022   Prob (F-statistic):           3.95e-45
Time:                        18:19:17   Log-Likelihood:                -509.89
No. Observations:                 200   AIC:                             1026.
Df Residuals:                     197   BIC:                             1036.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.7749      0.525     10.993      0.000       4.739       6.811
TV             0.0469      0.003     18.173      0.000       0.042       0.052
Newspaper      0.0442      0.010      4.346      0.000       0.024       0.064
==============================================================================
Omnibus:                        0.658   Durbin-Watson:                   1.969
Prob(Omnibus):                  0.720   Jarque-Bera (JB):                0.415
Skew:                          -0.093   Prob(JB):                        0.813
Kurtosis:                       3.122   Cond. No.                         410.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [5]:
lm3 = smf.ols(formula="Sales~TV+Radio", data = data).fit()
sales_pred = lm3.predict(data[["TV", "Radio"]])
SSD = sum((data["Sales"]-sales_pred)**2)
RSE = np.sqrt(SSD/(len(data)-2-1))

In [6]:
RSE

1.681360912508001